### ISSUE TITLE
"period" is added automatically

### ISSUE THREAD

**Issue by namwkim** [mrshahidlatif/vis-text-editor#73]
**Describe the bug**
"period" is added automatically

**To Reproduce**
1. Use the "trends.json" from [here](https://drive.google.com/drive/u/1/folders/1DjBxEjEptt5cNPJqtj12wShqb_Gi0zK3).
2. Type "daily_cases" and spacebar

**Expected behavior**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/70299/92266732-a3052e00-eead-11ea-9689-7a9edaaa5df4.png)

**Comment by mrshahidlatif** [comment]
I couldn't reproduce this. Probably some prior events lead to it.
